{{- if (include "portal.portalserverAuthCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.portalserverAuthSecretName" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data: 
  githubID: {{ .Values.portalServer.auth.github.id | b64enc | quote }}
  githubSecret: {{ .Values.portalServer.auth.github.secret | b64enc | quote }}
  googleID: {{ .Values.portalServer.auth.google.id | b64enc | quote }}
  googleSecret: {{ .Values.portalServer.auth.github.secret | b64enc | quote }}
{{- end -}}

