{{- if (include "portal.portalserverKeysCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.portalserverKeysSecretName" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.portalServer.keys.secret }}
  secret: {{ .Values.portalServer.keys.secret | b64enc | quote }}
  {{- else }}
  secret: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.portalServer.keys.passwordSalt }}
  passwordSalt: {{ .Values.portalServer.keys.passwordSalt | b64enc | quote }}
  {{- else }}
  passwordSalt: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.portalServer.keys.jwt }}
  jwt: {{ .Values.portalServer.keys.jwt | b64enc | quote }}
  {{- else }}
  jwt: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end -}}
