{{- if (include "portal.portalserverMailCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.portalserverMailSecretName" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data: 
  username: {{ .Values.portalServer.mail.username | b64enc | quote }}
  password: {{ .Values.portalServer.mail.password | b64enc | quote }}
{{- end -}}

