apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/portal/metrics"
  name: {{ include "portal.servername" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portalServer.service.type }}
  ports:
    - port: {{ .Values.portalServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "portal.portalServerSelectorLabels" . | nindent 4 }}
