{{- if (include "portal.DIDCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.DIDSecretName" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data:
  agentDID: {{ .Values.did.agentDID | b64enc | quote }}
  agentKeyName: {{ .Values.did.agentKeyName | b64enc | quote }}
  agentSecret: {{ .Values.did.agentSecret | b64enc | quote }}
  resolverUrl: {{ .Values.did.resolverUrl | b64enc | quote }}
  tokenDuration: {{ .Values.did.tokenDuration | b64enc | quote }}
  userDID: {{ .Values.did.userDID | b64enc | quote }}
{{- end -}}