apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.portalclientname" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.portalClient.replicaCount }}
  selector:
    matchLabels:
      {{- include "portal.portalClientSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: portal-client
        {{- include "portal.portalClientSelectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.portalClient.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.portalClient.securityContext | nindent 12 }}
          image: "{{ .Values.portalClient.image.repository }}:{{ .Values.portalClient.image.tag }}"
          imagePullPolicy: {{ .Values.portalClient.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.portalClient.resources | nindent 12 }}
    {{- with .Values.portalClient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portalClient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portalClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

